import { Book } from './types';

const KJ_URL = 'http://206.189.161.101:8080/api/kjbible/';
const STRONGS_URL = 'http://206.189.161.101:8080/api/strongsdata/';
const BOOK_LIST: Book[] = [
	{value: 'Genesis', label: 'Genesis', totalChapters: 50},
	{value: 'Exodus', label: 'Exodus', totalChapters: 40},
	{value: 'Leviticus', label: 'Leviticus',  totalChapters: 27},
	{value: 'Numbers', label: 'Numbers',  totalChapters: 36},
	{value: 'Deuteronomy', label: 'Deuteronomy',  totalChapters: 34},
	{value: 'Joshua', label: 'Joshua',  totalChapters: 24},
	{value: 'Judges', label: 'Judges',  totalChapters: 21},
	{value: 'Ruth', label: 'Ruth',  totalChapters: 4},
	{value: '1 Samuel', label: '1 Samuel',  totalChapters: 31},
	{value: '2 Samuel', label: '2 Samuel',  totalChapters: 24},
	{value: '1 Kings', label: '1 Kings',  totalChapters: 22},
	{value: '2 Kings', label: '2 Kings',  totalChapters: 25},
	{value: '1 Chronicles', label: '1 Chronicles',  totalChapters: 29},
	{value: '2 Chronicles', label: '2 Chronicles',  totalChapters: 36},
	{value: 'Ezra', label: 'Ezra',  totalChapters: 10},
	{value: 'Nehemiah', label: 'Nehemiah',  totalChapters: 13},
	{value: 'Esther', label: 'Esther',  totalChapters: 10},
	{value: 'Job', label: 'Job',  totalChapters: 42},
	{value: 'Psalms', label: 'Psalms',  totalChapters: 150},
	{value: 'Proverbs', label: 'Proverbs',  totalChapters: 31},
	{value: 'Ecclesiastes', label: 'Ecclesiastes',  totalChapters: 12},
	{value: 'Song of Solomon', label: 'Song of Solomon',  totalChapters: 8},
	{value: 'Isaiah', label: 'Isaiah',  totalChapters: 66},
	{value: 'Jeremiah', label: 'Jeremiah',  totalChapters: 52},
	{value: 'Lamentations', label: 'Lamentations',  totalChapters: 5},
	{value: 'Ezekiel', label: 'Ezekiel',  totalChapters: 48},
	{value: 'Daniel', label: 'Daniel',  totalChapters: 12},
	{value: 'Hosea', label: 'Hosea',  totalChapters: 14},
	{value: 'Joel', label: 'Joel',  totalChapters: 3},
	{value: 'Amos', label: 'Amos',  totalChapters: 9},
	{value: 'Obadiah', label: 'Obadiah',  totalChapters: 1},
	{value: 'Jonah', label: 'Jonah',  totalChapters: 4},
	{value: 'Micah', label: 'Micah',  totalChapters: 7},
	{value: 'Nahum', label: 'Nahum',  totalChapters: 3},
	{value: 'Habakkuk', label: 'Habakkuk',  totalChapters: 3},
	{value: 'Zephaniah', label: 'Zephaniah',  totalChapters: 3},
	{value: 'Haggai', label: 'Haggai',  totalChapters: 2},
	{value: 'Zechariah', label: 'Zechariah',  totalChapters: 14},
	{value: 'Malachi', label: 'Malachi',  totalChapters: 4},
	{value: 'Matthew', label: 'Matthew',  totalChapters: 28},
	{value: 'Mark', label: 'Mark',  totalChapters: 16},
	{value: 'Luke', label: 'Luke',  totalChapters: 24},
	{value: 'John', label: 'John',  totalChapters: 21},
	{value: 'Acts', label: 'Acts',  totalChapters: 28},
	{value: 'Romans', label: 'Romans',  totalChapters: 16},
	{value: '1 Corinthians', label: '1 Corinthians',  totalChapters: 16},
	{value: '2 Corinthians', label: '2 Corinthians',  totalChapters: 13},
	{value: 'Galatians', label: 'Galatians',  totalChapters: 6},
	{value: 'Ephesians', label: 'Ephesians',  totalChapters: 6},
	{value: 'Philippians', label: 'Philippians',  totalChapters: 4},
	{value: 'Colossians', label: 'Colossians',  totalChapters: 4},
	{value: '1 Thessalonians', label: '1 Thessalonians',  totalChapters: 5},
	{value: '2 Thessalonians', label: '2 Thessalonians',  totalChapters: 3},
	{value: '1 Timothy', label: '1 Timothy',  totalChapters: 6},
	{value: '2 Timothy', label: '2 Timothy',  totalChapters: 4},
	{value: 'Titus', label: 'Titus',  totalChapters: 3},
	{value: 'Philemon', label: 'Philemon',  totalChapters: 1},
	{value: 'Hebrews', label: 'Hebrews',  totalChapters: 13},
	{value: 'James', label: 'James',  totalChapters: 5},
	{value: '1 Peter', label: '1 Peter',  totalChapters: 5},
	{value: '2 Peter', label: '2 Peter',  totalChapters: 3},
	{value: '1 John', label: '1 John',  totalChapters: 5},
	{value: '2 John', label: '2 John',  totalChapters: 1},
	{value: '3 John', label: '3 John',  totalChapters: 1},
	{value: 'Jude', label: 'Jude',  totalChapters: 1},
	{value: 'Revelation', label: 'Revelation',  totalChapters: 22},
  ];

  export {
	  KJ_URL,
	  STRONGS_URL,
	  BOOK_LIST,
  }